volumes:
  database:

services:
  db:
    image: postgres
    environment:
      - TZ=Asia/Yangon
      - POSTGRES_USER=testdb
      - POSTGRES_PASSWORD=testdb
      - POSTGRES_DB=testdb
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data